from pathlib import Path
p=Path(r"C:\Users\L\Downloads\AI\mirae-ai-studio\deploy\web\index.html")
s=p.read_text(encoding="utf-8")
s=s.replace(':root{--bg:#fff;--panel:#f7f7f8;--text:#202123;--muted:#6b7280;--line:#e5e7eb;--soft:#f3f4f6;--accent:#111827;--sidebar:272px}', ':root{--bg:#fff;--panel:#f7f7f8;--text:#202123;--muted:#6b7280;--line:#e5e7eb;--soft:#f3f4f6;--accent:#111827;--sidebar:272px}html.dark{--bg:#212121;--panel:#171717;--text:#ececec;--muted:#a1a1aa;--line:#343434;--soft:#2a2a2a;--accent:#fff}')
s=s.replace('.app{height:100%;display:flex;overflow:hidden}', '.theme-dark .suggestion,.theme-dark .new-chat,.theme-dark .icon{background:#2a2a2a;color:#eee}.theme-dark .sidebar{background:#171717}.theme-dark .topbar{background:rgba(33,33,33,.9)}.theme-dark .composer-wrap{background:linear-gradient(transparent,#212121 30%)}.theme-dark .composer,.theme-dark .panel{background:#2a2a2a;color:#eee}.theme-dark .composer textarea,.theme-dark .panel input,.theme-dark .panel textarea,.theme-dark .panel select{color:#eee;background:#2a2a2a}.theme-dark .user .bubble{background:#343434}.app{height:100%;display:flex;overflow:hidden}')
s=s.replace('<div class="top-actions"><button class="icon" id="mobileNew" title="새 대화">＋</button></div>', '<div class="top-actions"><button class="icon" id="loginBtn" title="로그인">↪</button><button class="icon" id="mobileNew" title="새 대화">＋</button></div>')
s=s.replace('<button class="side-link" id="apiDocs">⌘ API 문서</button>', '<button class="side-link" id="apiDocs">⌘ API 문서</button><button class="side-link" id="apiKeys">⌕ API 키</button>')
s=s.replace('<div class="field"><label>인격</label>', '<div class="field"><label>디스플레이</label><select id="theme"><option value="system">시스템 맞춤</option><option value="dark">다크</option><option value="light">화이트</option></select></div><div class="field"><label>인격</label>')
s=s.replace('</div>\n</div>\n<script>', '''</div>
<div class="panel hidden" id="accountPanel"><div class="row"><h2>로그인</h2><button class="icon" id="accountClose">×</button></div><p style="color:var(--muted);font-size:12px">Mirae 계정으로 로그인하면 대화, API 키, 설정을 계정에 연결할 수 있습니다.</p><div class="field"><label>이메일</label><input id="loginEmail" type="email" placeholder="you@example.com"></div><div class="field"><label>비밀번호</label><input id="loginPassword" type="password" placeholder="비밀번호"></div><button class="new-chat" id="loginSubmit" style="background:#111;color:#fff;text-align:center">로그인</button><button class="side-link" id="signupBtn" style="justify-content:center;margin-top:6px">계정 만들기</button><p id="authStatus" style="color:#b45309;font-size:11px;margin-top:12px">계정 인증 서버 연결을 준비 중입니다.</p></div>
</div>
<script>''')
s=s.replace('$("#personality").value=settings.personality||"balanced";', '$("#theme").value=settings.theme||"system";$("#personality").value=settings.personality||"balanced";')
s=s.replace('const saveSettings=()=>localStorage.setItem("mirae-settings",JSON.stringify({personality:$("#personality").value,instructions:$("#instructions").value,web:$("#web").checked,temperature:Number($("#temp").value)}));', 'const saveSettings=()=>localStorage.setItem("mirae-settings",JSON.stringify({theme:$("#theme").value,personality:$("#personality").value,instructions:$("#instructions").value,web:$("#web").checked,temperature:Number($("#temp").value)})); function applyTheme(){const t=$("#theme").value;document.documentElement.classList.toggle("dark",t==="dark"||(t==="system"&&matchMedia("(prefers-color-scheme: dark)").matches));document.body.classList.toggle("theme-dark",document.documentElement.classList.contains("dark"));} applyTheme();')
s=s.replace('$("#newChat").onclick=newChat;$("#mobileNew").onclick=newChat;', '$("#newChat").onclick=newChat;$("#mobileNew").onclick=newChat;$("#theme").addEventListener("change",()=>{applyTheme();saveSettings()});matchMedia("(prefers-color-scheme: dark)").addEventListener("change",()=>{if($("#theme").value==="system")applyTheme()});$("#loginBtn").onclick=()=>$("#accountPanel").classList.toggle("hidden");$("#accountClose").onclick=()=>$("#accountPanel").classList.add("hidden");$("#apiKeys").onclick=()=>{location.href="/api-keys"};$("#loginSubmit").onclick=()=>{$("#authStatus").textContent="로그인 서버가 아직 이 정적 배포에 연결되지 않았습니다. 먼저 계정 백엔드를 연결해야 합니다.";};$("#signupBtn").onclick=()=>{$("#authStatus").textContent="회원가입 서버가 아직 연결되지 않았습니다.";};')
s=s.replace('$("#apiDocs").onclick=()=>location.href="/api-docs.html";', '$("#apiDocs").onclick=()=>location.href="/api-docs";')
p.write_text(s,encoding="utf-8")
