import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Copy, KeyRound, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ApiKeys() {
  const utils = trpc.useUtils(); const [name, setName] = useState(""); const [newKey, setNewKey] = useState<string | null>(null);
  const keys = trpc.studio.apiKeys.list.useQuery();
  const create = trpc.studio.apiKeys.create.useMutation({ onSuccess: ({ key }) => { setNewKey(key); setName(""); utils.studio.apiKeys.list.invalidate(); } });
  const revoke = trpc.studio.apiKeys.revoke.useMutation({ onSuccess: () => utils.studio.apiKeys.list.invalidate() });
  const copy = async () => { if (!newKey) return; await navigator.clipboard.writeText(newKey); toast.success("API 키를 복사했어요."); };
  const example = `curl -X POST http://127.0.0.1:8000/api/v1/chat/completions \\\n+  -H "Authorization: Bearer YOUR_MIRAE_API_KEY" \\\n+  -H "Content-Type: application/json" \\\n+  -d '{"message":"안녕하세요. Hello!"}'`;
  return <section className="mx-auto max-w-6xl space-y-6"><div><p className="mirae-kicker">PRIVATE GATEWAY</p><h1 className="mirae-page-title">당신의 AI를<br />안전하게 연결하세요.</h1></div><div className="grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="mirae-panel"><KeyRound className="size-5 text-teal-200" /><h2 className="mt-3">새 API 키</h2><p>키는 생성 직후 한 번만 표시됩니다. 복사한 뒤 안전하게 보관하세요.</p><div className="mt-5 flex gap-2"><Input value={name} onChange={e => setName(e.target.value)} placeholder="예: Unity prototype" className="border-white/10 bg-black/15 text-white placeholder:text-violet-200/45" /><Button onClick={() => create.mutate({ name })} disabled={name.trim().length < 2 || create.isPending} className="bg-teal-300 text-[#112423] hover:bg-teal-200"><Plus className="size-4" /></Button></div>{newKey && <div className="mt-4 rounded-xl border border-teal-200/25 bg-teal-200/10 p-3"><p className="mb-2 text-xs text-teal-100">이 창을 닫으면 전체 키는 다시 볼 수 없어요.</p><code className="block break-all text-xs text-white">{newKey}</code><Button size="sm" onClick={copy} className="mt-3 bg-white/10 text-white hover:bg-white/15"><Copy className="mr-1 size-3" />복사</Button></div>}</div><div className="mirae-panel"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-violet-200" /><h2>연결 예시</h2></div><p>발급한 키는 외부 요청의 `Authorization: Bearer` 또는 `X-API-Key` 헤더에 넣습니다.</p><pre className="mt-5 overflow-x-auto rounded-xl border border-white/10 bg-black/25 p-4 text-xs leading-6 text-teal-100"><code>{example}</code></pre></div></div><div className="mirae-panel overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><h2>발급된 키</h2><Badge className="border-0 bg-violet-300/15 text-violet-100">키는 해시로만 보관</Badge></div><div className="divide-y divide-white/8">{keys.data?.length ? keys.data.map(key => <div key={key.id} className="flex items-center justify-between gap-4 p-5"><div><p className="font-medium">{key.name}</p><p className="mt-1 font-mono text-xs text-violet-200">{key.keyPrefix}••••••</p></div><div className="flex items-center gap-3"><Badge className={key.state === "active" ? "border-0 bg-teal-200/15 text-teal-100" : "border-0 bg-white/10 text-violet-200"}>{key.state}</Badge>{key.state === "active" && <button onClick={() => revoke.mutate({ id: key.id })} className="text-violet-300 hover:text-rose-300" aria-label="키 폐기"><Trash2 className="size-4" /></button>}</div></div>) : <p className="p-6 text-sm text-violet-200">아직 발급된 키가 없습니다.</p>}</div></div></section>;
}
