import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Download, Lightbulb, Pencil, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

function downloadJsonl(filename: string, jsonl: string) { const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([jsonl], { type: "application/x-ndjson" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }

export default function TrainingData() {
  const utils = trpc.useUtils();
  const pairs = trpc.studio.trainingData.list.useQuery();
  const exported = trpc.studio.trainingData.exportJsonl.useQuery(undefined, { enabled: false });
  const create = trpc.studio.trainingData.create.useMutation({ onSuccess: () => { utils.studio.trainingData.list.invalidate(); toast.success("대화 쌍을 저장했어요."); } });
  const update = trpc.studio.trainingData.update.useMutation({ onSuccess: () => { utils.studio.trainingData.list.invalidate(); toast.success("대화 쌍을 수정했어요."); } });
  const remove = trpc.studio.trainingData.remove.useMutation({ onSuccess: () => utils.studio.trainingData.list.invalidate() });
  const suggest = trpc.studio.trainingData.suggest.useMutation();
  const [prompt, setPrompt] = useState(""); const [response, setResponse] = useState(""); const [seed, setSeed] = useState(""); const [editingId, setEditingId] = useState<number | null>(null);
  const save = () => { if (!prompt.trim() || !response.trim()) return toast.error("사용자와 어시스턴트 문장을 모두 입력해 주세요."); const payload = { prompt, response, language: "mixed" as const, status: "approved" as const }; if (editingId) update.mutate({ id: editingId, ...payload }); else create.mutate(payload); setPrompt(""); setResponse(""); setEditingId(null); };
  const exportFile = async () => { const data = await exported.refetch(); if (data.data) downloadJsonl(data.data.filename, data.data.jsonl); };
  return <section className="mx-auto max-w-6xl space-y-6"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="mirae-kicker">MEMORY ATELIER</p><h1 className="mirae-page-title">AI의 기억을<br />당신의 언어로 만드세요.</h1></div><Button onClick={exportFile} variant="outline" className="border-white/15 bg-white/[0.04] text-white hover:bg-white/10 hover:text-white"><Download className="mr-2 size-4" />JSONL 내보내기</Button></div>
    <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="mirae-panel space-y-4"><div className="flex items-center justify-between"><h2>{editingId ? "대화 쌍 수정" : "새 대화 쌍"}</h2>{editingId && <button onClick={() => { setEditingId(null); setPrompt(""); setResponse(""); }} className="text-xs text-teal-200">새로 작성</button>}</div><p>각 쌍은 모델이 배울 한 장면입니다. 자연스럽고 구체적으로 작성할수록 좋아요.</p><Textarea value={prompt} onChange={e => setPrompt(e.target.value)} placeholder="사용자: 오늘 너무 지쳤어." className="min-h-24 border-white/10 bg-black/15 text-white placeholder:text-violet-200/45" /><Textarea value={response} onChange={e => setResponse(e.target.value)} placeholder="어시스턴트: 그랬군요. 오늘을 버틴 것만으로도 충분해요." className="min-h-28 border-white/10 bg-black/15 text-white placeholder:text-violet-200/45" /><Button onClick={save} disabled={create.isPending || update.isPending} className="rounded-full bg-teal-300 text-[#112423] hover:bg-teal-200"><Plus className="mr-2 size-4" />{editingId ? "수정 저장" : "학습 기억으로 저장"}</Button></div>
      <div className="mirae-panel space-y-4"><div className="flex items-center gap-2"><Lightbulb className="size-5 text-teal-200" /><h2>로컬 초안 제안</h2></div><p>외부 LLM을 호출하지 않고, 검토 가능한 공감형 초안 두 개를 만듭니다. 마음에 드는 문장만 직접 수정해 저장하세요.</p><Input value={seed} onChange={e => setSeed(e.target.value)} placeholder="예: 새 프로젝트가 무서워" className="border-white/10 bg-black/15 text-white placeholder:text-violet-200/45" /><Button onClick={() => suggest.mutate({ seed })} disabled={!seed.trim() || suggest.isPending} variant="outline" className="border-teal-200/30 bg-teal-200/5 text-teal-100 hover:bg-teal-200/10 hover:text-white">초안 제안 받기</Button>{suggest.data?.suggestions.map((item, index) => <button key={index} onClick={() => { setPrompt(item.prompt); setResponse(item.response); }} className="w-full rounded-xl border border-white/10 bg-white/[0.04] p-3 text-left text-sm transition hover:border-teal-200/40"><span className="block text-teal-200">{item.prompt}</span><span className="mt-2 block text-violet-100/80">{item.response}</span></button>)}</div></div>
    <div className="mirae-panel overflow-hidden p-0"><div className="flex items-center justify-between border-b border-white/10 px-5 py-4"><h2>저장된 기억</h2><Badge className="border-0 bg-violet-300/15 text-violet-100">{pairs.data?.length ?? 0} pairs</Badge></div><div className="divide-y divide-white/8">{pairs.isLoading ? <p className="p-6 text-sm text-violet-200">불러오는 중...</p> : pairs.data?.length ? pairs.data.map(pair => <div key={pair.id} className="grid gap-3 p-5 md:grid-cols-[1fr_1fr_auto]"><p className="text-sm text-teal-100">{pair.prompt}</p><p className="text-sm text-violet-100/80">{pair.response}</p><div className="flex gap-3"><button onClick={() => { setEditingId(pair.id); setPrompt(pair.prompt); setResponse(pair.response); window.scrollTo({ top: 0, behavior: "smooth" }); }} className="self-start text-violet-300 hover:text-teal-200" aria-label="수정"><Pencil className="size-4" /></button><button onClick={() => remove.mutate({ id: pair.id })} className="self-start text-violet-300 hover:text-rose-300" aria-label="삭제"><Trash2 className="size-4" /></button></div></div>) : <p className="p-6 text-sm text-violet-200">아직 저장된 대화가 없어요. 첫 장면을 추가해 보세요.</p>}</div></div>
  </section>;
}
