import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { Activity, CircleDashed, Cpu, Gauge } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Training() {
  const utils = trpc.useUtils(); const [steps, setSteps] = useState(1000);
  const runs = trpc.studio.training.list.useQuery(undefined, { refetchInterval: 3000 });
  const start = trpc.studio.training.start.useMutation({ onSuccess: data => { utils.studio.training.list.invalidate(); toast.success(data.note); } });
  const latest = runs.data?.[0];
  return <section className="mx-auto max-w-6xl space-y-6"><div><p className="mirae-kicker">GROWTH OBSERVATORY</p><h1 className="mirae-page-title">작은 신호를 모아<br />AI를 키웁니다.</h1></div><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="mirae-panel"><div className="flex items-center gap-3"><Cpu className="size-6 text-teal-200" /><div><h2>새 학습 실행</h2><p>JSONL 데이터에서 직접 학습을 시작합니다.</p></div></div><div className="mt-6 flex flex-wrap items-center gap-3"><label className="text-sm text-violet-100">학습 스텝 <input type="number" min={100} max={20000} value={steps} onChange={e => setSteps(Number(e.target.value))} className="ml-2 w-28 rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-white" /></label><Button onClick={() => start.mutate({ steps })} className="rounded-full bg-teal-300 text-[#112423] hover:bg-teal-200">{start.isPending ? "요청 중" : "로컬 학습 요청"}</Button></div><p className="mt-4 text-xs leading-5 text-violet-200/70">웹 패널은 학습 요청과 지표를 기록합니다. 실제 PyTorch 학습은 ZIP에 포함된 Windows 로컬 런처가 실행하므로 외부 API나 클라우드 모델을 사용하지 않습니다.</p></div><div className="mirae-panel"><Gauge className="size-5 text-violet-200" /><h2 className="mt-3">현재 상태</h2>{latest ? <><div className="mt-5 flex items-center justify-between"><Badge className="border-0 bg-teal-200/15 text-teal-100">{latest.status}</Badge><span className="text-sm text-violet-100">{latest.currentStep} / {latest.requestedSteps}</span></div><Progress value={latest.progress} className="mt-3 h-2 bg-white/10" /><p className="mt-4 text-sm text-violet-100/75">손실값: {latest.loss?.toFixed(4) ?? "측정 대기"}</p><p className="mt-2 text-xs text-violet-200/60">{latest.note}</p></> : <p className="mt-4 text-sm text-violet-200">첫 학습 요청을 시작하면 진행률과 손실을 이곳에서 볼 수 있어요.</p>}</div></div><div className="mirae-panel"><div className="flex items-center gap-2"><Activity className="size-5 text-teal-200" /><h2>학습 기록</h2></div><div className="mt-5 grid gap-3">{runs.data?.length ? runs.data.map(run => <div key={run.id} className="rounded-xl bg-white/[0.045] px-4 py-3"><div className="flex justify-between text-sm"><span className="font-medium">{run.requestedSteps.toLocaleString()} steps</span><span className="text-teal-200">{run.status}</span></div><div className="mt-2 flex justify-between text-xs text-violet-200/70"><span>{run.progress}% complete</span><span>{run.loss ? `loss ${run.loss.toFixed(4)}` : "waiting"}</span></div></div>) : <div className="flex items-center gap-2 text-sm text-violet-200"><CircleDashed className="size-4" />아직 학습 기록이 없습니다.</div>}</div></div></section>;
}
